import type { AdminActionRequest } from './actionRequests'

const now = Date.now()

export const mockAdminActionRequests: AdminActionRequest[] = [
  {
    id: 'request-module-bayfront-service-signal',
    actionType: 'module_activation_change',
    title: 'Enable Service Signal / Paging for Bayfront Main Resort',
    requestedBy: { name: 'Team Happy Chair', email: 'owner@happychair.internal', role: 'Owner' },
    permissionRequired: 'modules.manage',
    scope: {
      organizationId: 'org-bayfront-resort',
      organizationName: 'Bayfront Resort Collection',
      propertyId: 'property-bayfront-main',
      propertyName: 'Bayfront Main Resort',
      label: 'Bayfront Main Resort',
    },
    status: 'Queued',
    reason: 'Trial setup is nearly complete and module routing needs server-side validation before activation.',
    auditEventId: 'audit-seed-module-action-request',
    rollbackNotes: 'Disable the activation record and restore the previous entitlement snapshot if dependency checks fail.',
    serverHandler: {
      key: 'server.modules.activation_change',
      label: 'Module activation handler',
      description: 'Placeholder for dependency checks, entitlement writes, audit entry, and activation rollback capture.',
      status: 'placeholder_only',
    },
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 14).toISOString(),
  },
  {
    id: 'request-remediation-pool-routing',
    actionType: 'remediation_server_action',
    title: 'Repair staff alert routing for Pool Service Deck',
    requestedBy: { name: 'Support Lead', email: 'support-lead@happychair.internal', role: 'Support Lead' },
    permissionRequired: 'troubleshooting.run',
    scope: {
      organizationId: 'org-bayfront-resort',
      organizationName: 'Bayfront Resort Collection',
      propertyId: 'property-bayfront-main',
      propertyName: 'Bayfront Main Resort',
      venueName: 'Pool Service Deck',
      label: 'Pool Service Deck',
    },
    status: 'Approved',
    reason: 'Support-safe runbook selected after module configuration signals showed incomplete routing.',
    auditEventId: 'audit-seed-remediation-action-request',
    rollbackNotes: 'Restore prior routing configuration and leave the remediation packet open if delivery checks fail.',
    serverHandler: {
      key: 'server.support.remediation_action',
      label: 'Remediation handler',
      description: 'Placeholder for scoped queue repair, module setup repair, and support-safe remediation execution.',
      status: 'placeholder_only',
    },
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 31).toISOString(),
  },
  {
    id: 'request-support-concourse-stalled-queue',
    actionType: 'support_troubleshooting_action',
    title: 'Move Concourse A stalled queue issue to engineering follow-up',
    requestedBy: { name: 'Engineering', email: 'engineering@happychair.internal', role: 'Engineering' },
    permissionRequired: 'troubleshooting.run',
    scope: {
      organizationId: 'org-stadium-north',
      organizationName: 'Stadium North Operations',
      propertyName: 'Stadium North Campus',
      venueName: 'Concourse A',
      label: 'Concourse A',
    },
    status: 'Running',
    reason: 'Escalation volume exceeded staffing coverage during event rush and needs a server-side activity record.',
    auditEventId: 'audit-seed-support-action-request',
    rollbackNotes: 'Keep the original support issue status and append a failed handler note if activity creation fails.',
    serverHandler: {
      key: 'server.support.troubleshooting_lifecycle',
      label: 'Support lifecycle handler',
      description: 'Placeholder for support issue status updates, escalation records, and visible activity entries.',
      status: 'placeholder_only',
    },
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 49).toISOString(),
  },
  {
    id: 'request-impersonation-happy-bistro-start',
    actionType: 'impersonation_start',
    title: 'Start scoped view-as session for Maria Garcia',
    requestedBy: { name: 'Support Lead', email: 'support-lead@happychair.internal', role: 'Support Lead' },
    permissionRequired: 'impersonation.start',
    scope: {
      organizationId: 'org-happy-bistro',
      organizationName: 'Happy Bistro Group',
      propertyId: 'property-cape-coral',
      propertyName: 'Cape Coral Property',
      venueId: 'venue-happy-bistro',
      venueName: 'Happy Bistro',
      label: 'Happy Bistro',
    },
    status: 'Completed',
    reason: 'Support verified notification routing during a customer call using a scoped, expiring session.',
    auditEventId: 'audit-seed-impersonation-action-request',
    rollbackNotes: 'Expire the session and preserve destructive-action block counters if session creation fails.',
    serverHandler: {
      key: 'server.impersonation.start',
      label: 'Impersonation start handler',
      description: 'Placeholder for secure view-as session creation with expiry, scope, permission, and audit controls.',
      status: 'placeholder_only',
    },
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 73).toISOString(),
  },
  {
    id: 'request-feature-flag-finance-provider',
    actionType: 'feature_flag_change',
    title: 'Enable finance provider sync in staging',
    requestedBy: { name: 'Engineering', email: 'engineering@happychair.internal', role: 'Engineering' },
    permissionRequired: 'feature_flags.manage',
    scope: { label: 'platform_admin.finance_provider_sync' },
    status: 'Blocked',
    reason: 'High-blast-radius billing integration requires owner-approved rollout notes before execution.',
    auditEventId: 'audit-seed-feature-flag-action-request',
    rollbackNotes: 'Return rollout to 0%, disable provider sync, and reconcile any created provider test records.',
    serverHandler: {
      key: 'server.feature_flags.change',
      label: 'Feature flag handler',
      description: 'Placeholder for rollout validation, blast-radius checks, audit writes, and rollback notes.',
      status: 'placeholder_only',
    },
    statusReason: 'owner_rollout_approval_missing',
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 94).toISOString(),
  },
  {
    id: 'request-billing-bayfront-discount-review',
    actionType: 'billing_review_action',
    title: 'Review Bayfront enterprise pilot discount',
    requestedBy: { name: 'Finance', email: 'finance@happychair.internal', role: 'Finance' },
    permissionRequired: 'billing.manage',
    scope: {
      organizationId: 'org-bayfront-resort',
      organizationName: 'Bayfront Resort Collection',
      label: 'Bayfront Resort Collection',
    },
    status: 'Draft',
    reason: 'Discount review is needed before conversion and before any provider-side billing change.',
    auditEventId: 'audit-seed-billing-action-request',
    rollbackNotes: 'Leave billing provider state untouched until finance approval and provider reconciliation are complete.',
    serverHandler: {
      key: 'server.billing.review_action',
      label: 'Billing review handler',
      description: 'Placeholder for finance-owned provider review, credit/refund/discount gates, and audit recording.',
      status: 'placeholder_only',
    },
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 118).toISOString(),
  },
  {
    id: 'request-agent-cs-upsell-review',
    actionType: 'agent_recommended_action',
    title: 'Approve Client Success Agent upsell recommendation',
    requestedBy: { name: 'Client Success Agent', role: 'Agent Draft' },
    permissionRequired: 'agents.manage',
    scope: {
      organizationId: 'org-happy-bistro',
      organizationName: 'Happy Bistro Group',
      venueId: 'venue-happy-bistro',
      venueName: 'Happy Bistro',
      label: 'Happy Bistro Group',
    },
    status: 'Queued',
    reason: 'Agent recommendation requires human approval before creating any customer-facing expansion workflow.',
    auditEventId: 'audit-seed-agent-action-request',
    rollbackNotes: 'Keep the recommendation in review state and do not create outreach, module, or billing records automatically.',
    serverHandler: {
      key: 'server.agents.approved_recommendation',
      label: 'Agent approval handler',
      description: 'Placeholder for human-approved agent recommendations that may later change client state.',
      status: 'placeholder_only',
    },
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 143).toISOString(),
  },
  {
    id: 'request-remediation-copper-qr-replay-failed',
    actionType: 'remediation_server_action',
    title: 'Replay failed QR session start for Copper Club Dining',
    requestedBy: { name: 'Support Agent', email: 'support-agent@happychair.internal', role: 'Support Agent' },
    permissionRequired: 'troubleshooting.run',
    scope: {
      organizationId: 'org-copper-club',
      organizationName: 'Copper Club Hospitality',
      propertyId: 'property-copper-main',
      propertyName: 'Copper Club Main',
      venueId: 'venue-copper-main',
      venueName: 'Copper Club Dining',
      label: 'Copper Club Dining',
    },
    status: 'Failed',
    reason: 'Session repair was queued from a support-safe runbook, but the handler requires fresh venue mapping evidence.',
    auditEventId: 'audit-seed-failed-remediation-action-request',
    rollbackNotes: 'No production write should be committed. Keep the remediation packet in engineering review.',
    serverHandler: {
      key: 'server.support.remediation_action',
      label: 'Remediation handler',
      description: 'Placeholder for scoped queue repair, module setup repair, and support-safe remediation execution.',
      status: 'placeholder_only',
    },
    statusReason: 'venue_mapping_evidence_missing',
    persistenceStatus: 'server_recorded',
    persistenceTarget: 'platform_admin.admin_action_requests',
    createdAt: new Date(now - 1000 * 60 * 166).toISOString(),
  },
]
