import {
  activityEvents,
  agentDefinitions,
  agentEvents,
  billingRisks,
  impersonationSessions,
  impersonationTargets,
  moduleActivations,
  moduleAdoption,
  moduleUsageGaps,
  organizations,
  platformHealthSignals,
  properties,
  registrations,
  revenueMetrics,
  supportIssues,
  supportNotes,
  usageAnalytics,
  venues,
} from '../mock-data/mockPlatform'
import type { PlatformAdminReadModel } from '../supabase/readContracts'

export const mockReadModel: PlatformAdminReadModel = {
  organizations,
  properties,
  venues,
  moduleActivations,
  moduleAdoption,
  moduleUsageGaps,
  registrations,
  revenueMetrics,
  billingRisks,
  supportIssues,
  platformHealthSignals,
  impersonationTargets,
  impersonationSessions,
  agentDefinitions,
  agentEvents,
  supportNotes,
  activityEvents,
  usageAnalytics,
}
